apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder-secret-sa
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: coder-secret-store
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: coder
          serviceAccountRef:
            name: coder-secret-sa
            audiences:
              - vault
      path: platform
      server: https://vault.kbntx.com
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-secret
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: coder-secret-store
    kind: SecretStore
  target:
    name: coder-secret
  dataFrom:
    - extract:
        key: coder
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-secret-user-credentials
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: coder-secret-store
    kind: SecretStore
  target:
    name: coder-secret-user-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: '{{ `{{ .postgresUser }}` }}'
        password: '{{ `{{ .postgresPassword }}` }}'
  dataFrom:
    - extract:
        key: coder
