apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.workspaceNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder-workspace-manager
  namespace: {{ .Values.workspaceNamespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services", "persistentvolumeclaims", "configmaps", "secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-workspace-manager
  namespace: {{ .Values.workspaceNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coder-workspace-manager
subjects:
  - kind: ServiceAccount
    name: {{ .Values.coder.coder.serviceAccount.name | default "coder" }}
    namespace: {{ .Release.Namespace }}
